# Site settings
title: Social Data Science
#email: andreas.bjerre-nielsen@econ.ku.dk
description: Summer School 2017<br/> Department of Economics<br/> University of Copenhagen
baseurl: "/sds2017"
url:  "abjer.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
